version: '3'
services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "supersecret"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - public

networks:
  public:

volumes:
  db-data:
